### PR TITLE
Simplified exports in blueprints

### LINKED ISSUE #134: Export classes directly instead of saving to variable
This is the way exporting is done at the moment:

```coffee
import Ember from 'ember'

ArticlesController = Ember.Controller.extend()

export default ArticlesController
```

This is because before CoffeeScript 1.12 when `export` and `import` were reserved words, we had to have those words on separate lines so we could surround them with backtics (which executes the code as JavaScript).

This isn't necessary anymore, so I think we should export directly to more closely resemble the built-in blueprints and learning material.

The above example would be like this:

```coffee
import Ember from 'ember'

export default Ember.Controller.extend()
```

### LINKED ISSUE #135: Generated code no longer pass the tests
Steps to reproduce:

```shell
ember new foo
cd foo
ember install ember-cli-coffeescript
ember g helper bar
ember test
```

produces the following error:
```shell
not ok 9 PhantomJS 2.1 - TestLoader Failures: foo/tests/unit/helpers/bar-test: could not be loaded
    ---
        actual: >
            null
        stack: >
            http://localhost:7357/assets/foo.js:46:22
            exports@http://localhost:7357/assets/vendor.js:140:37
            _reify@http://localhost:7357/assets/vendor.js:173:66
            reify@http://localhost:7357/assets/vendor.js:159:33
            exports@http://localhost:7357/assets/vendor.js:138:15
            requireModule@http://localhost:7357/assets/vendor.js:32:25
            require@http://localhost:7357/assets/test-support.js:4713:14
            loadModules@http://localhost:7357/assets/test-support.js:4705:21
            load@http://localhost:7357/assets/test-support.js:4735:33
            http://localhost:7357/assets/test-support.js:4619:22
        message: >
            Died on test #1 moduleLoadFailure@http://localhost:7357/assets/test-support.js:4607:17
            require@http://localhost:7357/assets/test-support.js:4715:29
            loadModules@http://localhost:7357/assets/test-support.js:4705:21
            load@http://localhost:7357/assets/test-support.js:4735:33
            http://localhost:7357/assets/test-support.js:4619:22: Strict mode forbids implicit creation of global property 'bar'
        Log: |
    ...
not ok 10 PhantomJS 2.1 - Global error: Error:
ReferenceError: Strict mode forbids implicit creation of global property 'bar' at http://localhost:7357/assets/test-support.js, line 4614
    ---
        Log: |
            { type: 'error',
              text: 'Error: \nReferenceError: Strict mode forbids implicit creation of global property \'bar\' at http://localhost:7357/assets/test-support.js, line 4614\n' }
    ...
not ok 11 PhantomJS 2.1 - TestLoader Failures: global failure
    ---
        actual: >
            null
        stack: >
            http://localhost:7357/assets/test-support.js:4614
        message: >
            Error:
            ReferenceError: Strict mode forbids implicit creation of global property 'bar'
        Log: |
    ...
```

This is due to the way the compiled file looks:

```js
define('foo/helpers/bar', ['exports', 'ember'], function (exports, _ember) {
  var BarHelper;

  exports.bar = bar = function (params) {
    return params;
  };

  BarHelper = _ember['default'].Helper.helper(bar);

  exports.bar = bar;
  exports['default'] = BarHelper;
});
```

The variable `bar` does not get defined properly. This issue is related to #134. Directly exporting the functions produces code that passes the tests.

This problem affects at least `helper`, `initializer`, `util`, `serializer`

@kimroen Do you want me to create a PR for the changes?

### PR DESCRIPTION
**Pull request by mriska**
This PR changes the blueprints from using a named variable to doing  direct exports of the code. In addition to being more easy on the eyes, it fixes a problem with the compiled javascript file containing an undeclared variable in newer versions of the CoffeeScript compiler.

Fixes #135 
Fixes #134

I have tested to create all of the blueprints changed: 
```shell
ember g adapter foo-foo
ember g component foo-foo
ember g controller foo-foo
ember g helper foo-foo
ember g mixin foo-foo
ember g model foo-foo
ember g route foo-foo
ember g serializer foo-foo
ember g service foo-foo
ember g transform foo-foo
ember g util foo-foo
ember g view foo-foo
```

And the tests pass with the exception of `view` which I assume is due to the fact that a fairly recent Ember version is used which no longer supports `view`s. I guess this blueprint can be removed at some point unless we want to keep it for people using it with older Ember version. On the other hand a case can be made for not helping them to create code that is deprecated in newer versions of Ember.

### CODE REVIEW

**Comment by mriska** [comment]
I didn't know there were node tests in here as well, I'll get those fixed.

**Comment by mriska** [comment]
@kimroen pushed updated code with amended tests. There is only one failure (beta) in Travis right now that looks like it needs poking to be rerun.

**Comment by mriska** [comment]
@kimroen, All builds are green now, do you think it should be merged, or are you still missing something?

File: blueprints/util/files/__root__/utils/__name__.coffee [hunk 1]
```diff
@@ -1,4 +1,2 @@
-<%= camelizedModuleName %> = () ->
+export default () ->
```
Comment (kimroen) [inline blueprints/util/files/__root__/utils/__name__.coffee]: In [the original blueprint](https://github.com/ember-cli/ember-cli-legacy-blueprints/blob/master/blueprints/util/files/__root__/utils/__name__.js) this is a named function, but I haven't found a way to export a named function with the CoffeeScript syntax, so I'm not sure if it can be done.

**Comment by kimroen** [comment]
This looks good - thanks again! 🎉

File: blueprints/util/files/__root__/utils/__name__.coffee (hunk 1 above)
Comment (mriska) [inline blueprints/util/files/__root__/utils/__name__.coffee]: @kimroen I think you can do that with
```coffeescript
export <%= camelizedModuleName %> () -> 
```

Like we have done here: https://github.com/kimroen/ember-cli-coffeescript/pull/137/files#diff-f9c146914b83a86c6a8d484dc1d877d6R4

Comment (mriska) [inline blueprints/util/files/__root__/utils/__name__.coffee]: I'll do some testing and create a PR for that.

**Comment by kimroen** [comment]
I noticed now that this missed some files, like the [initializers](https://github.com/kimroen/ember-cli-coffeescript/blob/master/blueprints/initializer/files/__root__/initializers/__name__.coffee).

**Comment by mriska** [comment]
@kimroen I'll check those out later today/tonight

**Comment by mriska** [comment]
@kimroen Created a new PR #139 that fixes `initializer` blueprint.
